export const LOGIN = 'LOGIN';
export const LOGIN_COMPLETE = 'LOGIN_COMPLETE';
export const RECEIVE_FIREBASE_LIST = 'RECEIVE_FIREBASE_LIST';
export const CREATE_CHAT_ITEM = 'CREATE_CHAT_ITEM';
export const CREATE_NEW_USER = 'CREATE_NEW_USER'