const Constants = {
	FIREBASE: 'https://travcast.firebaseio.com',

	// AUTH ACTIONS
	ATTEMPTING_LOGIN: 'ATTEMPTING_LOGIN',
	LOGIN_USER: 'LOGIN_USER',
	LOGOUT: 'LOGOUT',

	// AUTH STATES
	LOGGED_IN: 'LOGGED_IN',
	ANONYMOUS: 'ANONYMOUS',
	AWAITING_AUTH_RESPONSE: 'AWAITING_AUTH_RESPONSE',

	// UI FEEDBACK ACTIONS
	DISPLAY_ERROR: "DISPLAY_ERROR",
	DISPLAY_MESSAGE: "DISPLAY_MESSAGE",
	DISMISS_FEEDBACK: "DISMISS_FEEDBACK"

};

export default Constants